In [20]:
import pandas as pd

##### We import the file from the local directory.

In [21]:
df = pd.read_csv("C:/Users/User/Desktop/MLAI/clv-model/eda/ecommerce_data.csv")

##### Load the first twenty rows of the dataset to get a general idea of the dataset.

In [22]:
df.head(20)

,CustomerID,InvoiceDate,Quantity,UnitPrice,TotalAmount,Country,ProductCategory
0,C0045,2022-08-24 00:00:00,2,39.69,79.39,UK,Books
1,C0757,2022-07-01 00:00:00,1,414.09,414.09,Netherlands,Sports
2,C1643,2022-01-05 00:00:00,1,358.44,358.44,NaN,Sports
3,C0133,2023-07-01 00:00:00,1,150.21,150.21,UK,Clothing
4,C0941,2022-12-10 00:00:00,1,222.65,222.65,UK,Sports
5,C0802,2023-02-20 00:00:00,1,31.98,31.98,UK,Beauty
6,C1284,2022-12-04 00:00:00,1,678.76,678.76,Italy,Electronics
7,C1706,2022-04-24 00:00:00,1,150.28,127.41,UK,Clothing
8,C1608,2022-11-12 00:00:00,1,37.89,37.89,UK,Beauty
9,C0759,2023-03-19 00:00:00,1,38.60,38.60,Spain,Beauty
10,C1735,2022-10-03 00:00:00,1,54.05,54.05,Germany,Beauty
11,C0562,2022-04-20 00:00:00,1,58.12,58.12,UK,Beauty
12,C0363,2023-03-29 00:00:00,1,159.31,159.31,UK,Sports
13,C0224,2022-10-24 00:00:00,1,446.87,446.87,UK,Sports
14,C1802,2022-11-12 00:00:00,1,602.07,602.07,NaN,Electronics
15,C0970,2022-11-02 00:00:00,5,38.72,193.61,UK,Books
16,C0019,2022-08-20 00:00:00,1,9.65,9.65,France,Books
17,C0790,2022-12-04 00:00:00,1,502.04,502.04,UK,Electronics
18,C0109,2022-07-31 00:00:00,1,96.24,96.24,NaN,Home & Garden
19,C1591,2022-11-01 00:00:00,1,48.96,48.96,Spain,Clothing

##### Review the Country column and identify missing values

In [23]:
missing_count = df["Country"].isnull().sum()
print("Missing Country values:", missing_count)

Missing Country values: 1339

##### The percentage of missing countries

In [24]:
missing_percentage = df["Country"].isnull().mean() * 100 
print("Missing Country values:", missing_count)
print("Percentage missing:", round(missing_percentage, 2), "%")

Missing Country values: 1339
Percentage missing: 16.32 %

##### Basically, we cannot drop the missing data from about 1,339 countries because doing so would result in a significant loss of data and could affect the accuracy of the results. We will investigate before trying to fill this missing values with 'unknown'

##### Rows with missing Country values

In [25]:
missing_country = df[df["Country"].isnull()]
missing_country = df["Country"].isna().sum()
missing_country.head(10)

AttributeError: 'numpy.int64' object has no attribute 'head'

Total records: 8205
Missing Country values: 0
Percentage missing: 0.0 %

##### We are going to check for repeated customer records

In [ ]:
if "CustomerID" in df.columns:

    missing_customers = df.loc[
        df["Country"].isna(), "CustomerID"
    ].dropna().unique()

    customer_records = df[
        df["CustomerID"].isin(missing_customers)
    ]

    print("\nRecords belonging to customers with missing countries:")
    print(
        customer_records[["CustomerID", "Country"]]
        .sort_values("CustomerID")
        .to_string(index=False)
    )

Records belonging to customers with missing countries:
CustomerID Country
     C0003     NaN
     C0003     NaN
     C0003     NaN
     C0003     NaN
     C0003     NaN
     C0003     NaN
     C0003     NaN
     C0003     NaN
     C0004     NaN
     C0004     NaN
     C0013     NaN
     C0017     NaN
     C0017     NaN
     C0017     NaN
     C0022     NaN
     C0022     NaN
     C0022     NaN
     C0022     NaN
     C0022     NaN
     C0023     NaN
     C0023     NaN
     C0023     NaN
     C0023     NaN
     C0023     NaN
     C0023     NaN
     C0023     NaN
     C0023     NaN
     C0029     NaN
     C0033     NaN
     C0033     NaN
     C0033     NaN
     C0033     NaN
     C0033     NaN
     C0033     NaN
     C0033     NaN
     C0033     NaN
     C0033     NaN
     C0033     NaN
     C0033     NaN
     C0033     NaN
     C0037     NaN
     C0037     NaN
     C0037     NaN
     C0037     NaN
     C0037     NaN
     C0037     NaN
     C0054     NaN
     C0060     NaN
     C0066     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0067     NaN
     C0071     NaN
     C0071     NaN
     C0075     NaN
     C0075     NaN
     C0075     NaN
     C0075     NaN
     C0075     NaN
     C0075     NaN
     C0079     NaN
     C0087     NaN
     C0087     NaN
     C0088     NaN
     C0088     NaN
     C0088     NaN
     C0088     NaN
     C0088     NaN
     C0095     NaN
     C0100     NaN
     C0100     NaN
     C0100     NaN
     C0100     NaN
     C0100     NaN
     C0100     NaN
     C0100     NaN
     C0100     NaN
     C0100     NaN
     C0100     NaN
     C0100     NaN
     C0105     NaN
     C0109     NaN
     C0109     NaN
     C0109     NaN
     C0109     NaN
     C0109     NaN
     C0109     NaN
     C0109     NaN
     C0109     NaN
     C0109     NaN
     C0109     NaN
     C0109     NaN
     C0109     NaN
     C0109     NaN
     C0109     NaN
     C0109     NaN
     C0112     NaN
     C0112     NaN
     C0112     NaN
     C0112     NaN
     C0112     NaN
     C0116     NaN
     C0123     NaN
     C0123     NaN
     C0127     NaN
     C0127     NaN
     C0127     NaN
     C0129     NaN
     C0129     NaN
     C0134     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0137     NaN
     C0144     NaN
     C0144     NaN
     C0144     NaN
     C0144     NaN
     C0144     NaN
     C0146     NaN
     C0146     NaN
     C0146     NaN
     C0146     NaN
     C0153     NaN
     C0153     NaN
     C0153     NaN
     C0153     NaN
     C0153     NaN
     C0153     NaN
     C0153     NaN
     C0153     NaN
     C0153     NaN
     C0156     NaN
     C0158     NaN
     C0161     NaN
     C0163     NaN
     C0163     NaN
     C0163     NaN
     C0163     NaN
     C0163     NaN
     C0176     NaN
     C0179     NaN
     C0179     NaN
     C0179     NaN
     C0179     NaN
     C0179     NaN
     C0193     NaN
     C0193     NaN
     C0193     NaN
     C0193     NaN
     C0193     NaN
     C0193     NaN
     C0193     NaN
     C0193     NaN
     C0193     NaN
     C0193     NaN
     C0193     NaN
     C0193     NaN
     C0209     NaN
     C0215     NaN
     C0234     NaN
     C0238     NaN
     C0238     NaN
     C0238     NaN
     C0238     NaN
     C0238     NaN
     C0239     NaN
     C0239     NaN
     C0239     NaN
     C0239     NaN
     C0239     NaN
     C0239     NaN
     C0239     NaN
     C0239     NaN
     C0239     NaN
     C0239     NaN
     C0256     NaN
     C0256     NaN
     C0256     NaN
     C0256     NaN
     C0256     NaN
     C0256     NaN
     C0256     NaN
     C0256     NaN
     C0256     NaN
     C0256     NaN
     C0256     NaN
     C0256     NaN
     C0256     NaN
     C0256     NaN
     C0256     NaN
     C0256     NaN
     C0265     NaN
     C0293     NaN
     C0293     NaN
     C0293     NaN
     C0293     NaN
     C0293     NaN
     C0293     NaN
     C0293     NaN
     C0293     NaN
     C0293     NaN
     C0293     NaN
     C0293     NaN
     C0293     NaN
     C0293     NaN
     C0293     NaN
     C0293     NaN
     C0293     NaN
     C0293     NaN
     C0293     NaN
     C0295     NaN
     C0295     NaN
     C0295     NaN
     C0295     NaN
     C0297     NaN
     C0297     NaN
     C0297     NaN
     C0297     NaN
     C0297     NaN
     C0303     NaN
     C0317     NaN
     C0317     NaN
     C0317     NaN
     C0317     NaN
     C0317     NaN
     C0317     NaN
     C0317     NaN
     C0317     NaN
     C0317     NaN
     C0317     NaN
     C0317     NaN
     C0317     NaN
     C0317     NaN
     C0317     NaN
     C0328     NaN
     C0328     NaN
     C0328     NaN
     C0341     NaN
     C0341     NaN
     C0341     NaN
     C0341     NaN
     C0342     NaN
     C0350     NaN
     C0351     NaN
     C0351     NaN
     C0351     NaN
     C0351     NaN
     C0351     NaN
     C0351     NaN
     C0351     NaN
     C0351     NaN
     C0351     NaN
     C0353     NaN
     C0353     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0354     NaN
     C0355     NaN
     C0355     NaN
     C0355     NaN
     C0355     NaN
     C0355     NaN
     C0355     NaN
     C0355     NaN
     C0355     NaN
     C0355     NaN
     C0355     NaN
     C0359     NaN
     C0359     NaN
     C0359     NaN
     C0359     NaN
     C0359     NaN
     C0359     NaN
     C0371     NaN
     C0373     NaN
     C0382     NaN
     C0382     NaN
     C0382     NaN
     C0382     NaN
     C0387     NaN
     C0389     NaN
     C0389     NaN
     C0389     NaN
     C0389     NaN
     C0392     NaN
     C0392     NaN
     C0392     NaN
     C0392     NaN
     C0392     NaN
     C0404     NaN
     C0404     NaN
     C0404     NaN
     C0406     NaN
     C0406     NaN
     C0406     NaN
     C0406     NaN
     C0406     NaN
     C0406     NaN
     C0406     NaN
     C0406     NaN
     C0406     NaN
     C0406     NaN
     C0406     NaN
     C0406     NaN
     C0406     NaN
     C0406     NaN
     C0406     NaN
     C0406     NaN
     C0406     NaN
     C0406     NaN
     C0414     NaN
     C0414     NaN
     C0414     NaN
     C0414     NaN
     C0414     NaN
     C0414     NaN
     C0414     NaN
     C0415     NaN
     C0422     NaN
     C0427     NaN
     C0437     NaN
     C0437     NaN
     C0437     NaN
     C0437     NaN
     C0442     NaN
     C0442     NaN
     C0442     NaN
     C0442     NaN
     C0442     NaN
     C0442     NaN
     C0442     NaN
     C0442     NaN
     C0442     NaN
     C0442     NaN
     C0442     NaN
     C0442     NaN
     C0444     NaN
     C0444     NaN
     C0444     NaN
     C0452     NaN
     C0452     NaN
     C0458     NaN
     C0458     NaN
     C0458     NaN
     C0458     NaN
     C0458     NaN
     C0458     NaN
     C0459     NaN
     C0459     NaN
     C0461     NaN
     C0467     NaN
     C0480     NaN
     C0480     NaN
     C0480     NaN
     C0480     NaN
     C0480     NaN
     C0480     NaN
     C0480     NaN
     C0480     NaN
     C0480     NaN
     C0480     NaN
     C0480     NaN
     C0480     NaN
     C0480     NaN
     C0480     NaN
     C0482     NaN
     C0482     NaN
     C0489     NaN
     C0489     NaN
     C0489     NaN
     C0489     NaN
     C0489     NaN
     C0502     NaN
     C0502     NaN
     C0502     NaN
     C0502     NaN
     C0502     NaN
     C0502     NaN
     C0509     NaN
     C0509     NaN
     C0509     NaN
     C0509     NaN
     C0509     NaN
     C0509     NaN
     C0514     NaN
     C0517     NaN
     C0517     NaN
     C0517     NaN
     C0517     NaN
     C0517     NaN
     C0517     NaN
     C0517     NaN
     C0520     NaN
     C0521     NaN
     C0521     NaN
     C0521     NaN
     C0521     NaN
     C0521     NaN
     C0521     NaN
     C0521     NaN
     C0522     NaN
     C0527     NaN
     C0527     NaN
     C0527     NaN
     C0532     NaN
     C0532     NaN
     C0532     NaN
     C0532     NaN
     C0532     NaN
     C0532     NaN
     C0532     NaN
     C0532     NaN
     C0532     NaN
     C0532     NaN
     C0532     NaN
     C0532     NaN
     C0532     NaN
     C0532     NaN
     C0532     NaN
     C0535     NaN
     C0535     NaN
     C0535     NaN
     C0535     NaN
     C0535     NaN
     C0535     NaN
     C0535     NaN
     C0544     NaN
     C0548     NaN
     C0548     NaN
     C0556     NaN
     C0558     NaN
     C0568     NaN
     C0568     NaN
     C0568     NaN
     C0568     NaN
     C0575     NaN
     C0575     NaN
     C0575     NaN
     C0575     NaN
     C0575     NaN
     C0575     NaN
     C0582     NaN
     C0586     NaN
     C0586     NaN
     C0588     NaN
     C0588     NaN
     C0590     NaN
     C0595     NaN
     C0599     NaN
     C0608     NaN
     C0618     NaN
     C0618     NaN
     C0618     NaN
     C0618     NaN
     C0618     NaN
     C0618     NaN
     C0618     NaN
     C0618     NaN
     C0618     NaN
     C0618     NaN
     C0618     NaN
     C0618     NaN
     C0620     NaN
     C0620     NaN
     C0620     NaN
     C0620     NaN
     C0620     NaN
     C0632     NaN
     C0639     NaN
     C0639     NaN
     C0639     NaN
     C0643     NaN
     C0646     NaN
     C0646     NaN
     C0646     NaN
     C0650     NaN
     C0650     NaN
     C0650     NaN
     C0653     NaN
     C0656     NaN
     C0660     NaN
     C0660     NaN
     C0664     NaN
     C0664     NaN
     C0664     NaN
     C0664     NaN
     C0664     NaN
     C0664     NaN
     C0674     NaN
     C0678     NaN
     C0678     NaN
     C0678     NaN
     C0678     NaN
     C0678     NaN
     C0678     NaN
     C0678     NaN
     C0678     NaN
     C0678     NaN
     C0678     NaN
     C0678     NaN
     C0678     NaN
     C0678     NaN
     C0680     NaN
     C0680     NaN
     C0680     NaN
     C0680     NaN
     C0681     NaN
     C0681     NaN
     C0681     NaN
     C0681     NaN
     C0681     NaN
     C0681     NaN
     C0702     NaN
     C0702     NaN
     C0702     NaN
     C0711     NaN
     C0711     NaN
     C0711     NaN
     C0711     NaN
     C0711     NaN
     C0711     NaN
     C0711     NaN
     C0711     NaN
     C0712     NaN
     C0724     NaN
     C0724     NaN
     C0726     NaN
     C0726     NaN
     C0726     NaN
     C0726     NaN
     C0726     NaN
     C0726     NaN
     C0726     NaN
     C0726     NaN
     C0726     NaN
     C0726     NaN
     C0733     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0743     NaN
     C0745     NaN
     C0762     NaN
     C0773     NaN
     C0773     NaN
     C0773     NaN
     C0773     NaN
     C0773     NaN
     C0773     NaN
     C0773     NaN
     C0773     NaN
     C0780     NaN
     C0786     NaN
     C0786     NaN
     C0786     NaN
     C0786     NaN
     C0786     NaN
     C0786     NaN
     C0786     NaN
     C0786     NaN
     C0787     NaN
     C0787     NaN
     C0787     NaN
     C0787     NaN
     C0796     NaN
     C0796     NaN
     C0796     NaN
     C0796     NaN
     C0798     NaN
     C0798     NaN
     C0798     NaN
     C0808     NaN
     C0810     NaN
     C0815     NaN
     C0817     NaN
     C0817     NaN
     C0817     NaN
     C0817     NaN
     C0817     NaN
     C0831     NaN
     C0831     NaN
     C0831     NaN
     C0837     NaN
     C0837     NaN
     C0837     NaN
     C0837     NaN
     C0837     NaN
     C0837     NaN
     C0845     NaN
     C0851     NaN
     C0851     NaN
     C0851     NaN
     C0851     NaN
     C0851     NaN
     C0851     NaN
     C0851     NaN
     C0864     NaN
     C0864     NaN
     C0864     NaN
     C0864     NaN
     C0864     NaN
     C0864     NaN
     C0872     NaN
     C0874     NaN
     C0874     NaN
     C0874     NaN
     C0874     NaN
     C0874     NaN
     C0874     NaN
     C0874     NaN
     C0874     NaN
     C0874     NaN
     C0874     NaN
     C0874     NaN
     C0874     NaN
     C0874     NaN
     C0874     NaN
     C0874     NaN
     C0874     NaN
     C0874     NaN
     C0882     NaN
     C0882     NaN
     C0882     NaN
     C0882     NaN
     C0882     NaN
     C0882     NaN
     C0882     NaN
     C0882     NaN
     C0896     NaN
     C0896     NaN
     C0902     NaN
     C0902     NaN
     C0908     NaN
     C0908     NaN
     C0908     NaN
     C0908     NaN
     C0908     NaN
     C0908     NaN
     C0908     NaN
     C0908     NaN
     C0908     NaN
     C0908     NaN
     C0919     NaN
     C0919     NaN
     C0919     NaN
     C0919     NaN
     C0919     NaN
     C0919     NaN
     C0919     NaN
     C0919     NaN
     C0922     NaN
     C0934     NaN
     C0934     NaN
     C0934     NaN
     C0937     NaN
     C0939     NaN
     C0939     NaN
     C0939     NaN
     C0939     NaN
     C0939     NaN
     C0939     NaN
     C0939     NaN
     C0939     NaN
     C0945     NaN
     C0947     NaN
     C0947     NaN
     C0947     NaN
     C0947     NaN
     C0955     NaN
     C0955     NaN
     C0955     NaN
     C0955     NaN
     C0955     NaN
     C0955     NaN
     C0958     NaN
     C0958     NaN
     C0958     NaN
     C0958     NaN
     C0958     NaN
     C0958     NaN
     C0958     NaN
     C0958     NaN
     C0958     NaN
     C0958     NaN
     C0958     NaN
     C0958     NaN
     C0959     NaN
     C0959     NaN
     C0959     NaN
     C0959     NaN
     C0959     NaN
     C0959     NaN
     C0959     NaN
     C0961     NaN
     C0961     NaN
     C0961     NaN
     C0961     NaN
     C0965     NaN
     C0974     NaN
     C0984     NaN
     C0987     NaN
     C0987     NaN
     C0987     NaN
     C0987     NaN
     C0987     NaN
     C0987     NaN
     C0987     NaN
     C0987     NaN
     C0987     NaN
     C0987     NaN
     C0987     NaN
     C0987     NaN
     C0987     NaN
     C0988     NaN
     C0988     NaN
     C0988     NaN
     C0989     NaN
     C0989     NaN
     C1001     NaN
     C1001     NaN
     C1012     NaN
     C1015     NaN
     C1015     NaN
     C1015     NaN
     C1015     NaN
     C1015     NaN
     C1018     NaN
     C1018     NaN
     C1018     NaN
     C1018     NaN
     C1018     NaN
     C1018     NaN
     C1018     NaN
     C1018     NaN
     C1018     NaN
     C1027     NaN
     C1027     NaN
     C1027     NaN
     C1046     NaN
     C1046     NaN
     C1046     NaN
     C1046     NaN
     C1046     NaN
     C1046     NaN
     C1046     NaN
     C1046     NaN
     C1046     NaN
     C1046     NaN
     C1047     NaN
     C1050     NaN
     C1050     NaN
     C1050     NaN
     C1060     NaN
     C1070     NaN
     C1074     NaN
     C1079     NaN
     C1079     NaN
     C1079     NaN
     C1079     NaN
     C1079     NaN
     C1081     NaN
     C1081     NaN
     C1081     NaN
     C1081     NaN
     C1090     NaN
     C1090     NaN
     C1090     NaN
     C1090     NaN
     C1090     NaN
     C1090     NaN
     C1090     NaN
     C1092     NaN
     C1092     NaN
     C1092     NaN
     C1092     NaN
     C1092     NaN
     C1092     NaN
     C1092     NaN
     C1092     NaN
     C1092     NaN
     C1092     NaN
     C1092     NaN
     C1092     NaN
     C1092     NaN
     C1092     NaN
     C1112     NaN
     C1112     NaN
     C1112     NaN
     C1112     NaN
     C1112     NaN
     C1112     NaN
     C1116     NaN
     C1116     NaN
     C1118     NaN
     C1118     NaN
     C1118     NaN
     C1118     NaN
     C1118     NaN
     C1118     NaN
     C1118     NaN
     C1118     NaN
     C1118     NaN
     C1118     NaN
     C1118     NaN
     C1118     NaN
     C1119     NaN
     C1119     NaN
     C1119     NaN
     C1119     NaN
     C1119     NaN
     C1128     NaN
     C1128     NaN
     C1128     NaN
     C1128     NaN
     C1128     NaN
     C1128     NaN
     C1128     NaN
     C1128     NaN
     C1128     NaN
     C1140     NaN
     C1140     NaN
     C1163     NaN
     C1168     NaN
     C1168     NaN
     C1168     NaN
     C1168     NaN
     C1168     NaN
     C1168     NaN
     C1168     NaN
     C1168     NaN
     C1168     NaN
     C1168     NaN
     C1168     NaN
     C1168     NaN
     C1168     NaN
     C1168     NaN
     C1168     NaN
     C1174     NaN
     C1204     NaN
     C1204     NaN
     C1204     NaN
     C1204     NaN
     C1215     NaN
     C1215     NaN
     C1218     NaN
     C1219     NaN
     C1230     NaN
     C1230     NaN
     C1230     NaN
     C1230     NaN
     C1230     NaN
     C1230     NaN
     C1230     NaN
     C1230     NaN
     C1230     NaN
     C1230     NaN
     C1230     NaN
     C1230     NaN
     C1230     NaN
     C1230     NaN
     C1230     NaN
     C1230     NaN
     C1230     NaN
     C1230     NaN
     C1230     NaN
     C1234     NaN
     C1234     NaN
     C1273     NaN
     C1273     NaN
     C1273     NaN
     C1273     NaN
     C1274     NaN
     C1274     NaN
     C1274     NaN
     C1274     NaN
     C1274     NaN
     C1274     NaN
     C1274     NaN
     C1274     NaN
     C1274     NaN
     C1274     NaN
     C1274     NaN
     C1274     NaN
     C1288     NaN
     C1297     NaN
     C1297     NaN
     C1297     NaN
     C1297     NaN
     C1297     NaN
     C1298     NaN
     C1303     NaN
     C1310     NaN
     C1313     NaN
     C1316     NaN
     C1316     NaN
     C1316     NaN
     C1316     NaN
     C1316     NaN
     C1321     NaN
     C1321     NaN
     C1321     NaN
     C1321     NaN
     C1321     NaN
     C1327     NaN
     C1327     NaN
     C1332     NaN
     C1332     NaN
     C1332     NaN
     C1332     NaN
     C1332     NaN
     C1332     NaN
     C1332     NaN
     C1332     NaN
     C1332     NaN
     C1332     NaN
     C1332     NaN
     C1332     NaN
     C1345     NaN
     C1345     NaN
     C1345     NaN
     C1345     NaN
     C1345     NaN
     C1345     NaN
     C1345     NaN
     C1345     NaN
     C1350     NaN
     C1350     NaN
     C1350     NaN
     C1350     NaN
     C1350     NaN
     C1350     NaN
     C1350     NaN
     C1350     NaN
     C1350     NaN
     C1364     NaN
     C1364     NaN
     C1364     NaN
     C1365     NaN
     C1365     NaN
     C1365     NaN
     C1365     NaN
     C1365     NaN
     C1365     NaN
     C1365     NaN
     C1365     NaN
     C1365     NaN
     C1365     NaN
     C1365     NaN
     C1365     NaN
     C1365     NaN
     C1365     NaN
     C1382     NaN
     C1383     NaN
     C1383     NaN
     C1386     NaN
     C1387     NaN
     C1387     NaN
     C1388     NaN
     C1388     NaN
     C1388     NaN
     C1388     NaN
     C1393     NaN
     C1393     NaN
     C1393     NaN
     C1393     NaN
     C1393     NaN
     C1393     NaN
     C1393     NaN
     C1393     NaN
     C1393     NaN
     C1393     NaN

##### Count customer with distinct missing Country values

In [ ]:
print("Customers with missing Country:", df.loc[df["Country"].isna(), "CustomerID"].nunique())

Customers with missing Country: 281


##### Find customers with missing countries who also have at least one known country elsewhere in the dataset

In [ ]:
known_country_customers = df.loc[
    df["Country"].notna(), "CustomerID"
].unique()

In [ ]:
recoverable = df.loc[
    df["Country"].isna()
    & df["CustomerID"].isin(known_country_customers),
    "CustomerID"
].nunique()

print("Customers potentially recoverable:", recoverable)

Customers potentially recoverable: 0

##### This code displays all rows with missing countries, checks other columns for missing countries and checks missing-value counts in these rows

In [ ]:
missing_country = df[df["Country"].isna()]

print(missing_country.head(10).to_string(index=False))
print(missing_country.isna().sum())

CustomerID         InvoiceDate  Quantity  UnitPrice  TotalAmount Country ProductCategory
     C1643 2022-01-05 00:00:00         1     358.44       358.44     NaN          Sports
     C1802 2022-11-12 00:00:00         1     602.07       602.07     NaN     Electronics
     C0109 2022-07-31 00:00:00         1      96.24        96.24     NaN   Home & Garden
     C0902 2022-10-31 00:00:00         1      42.46        42.46     NaN          Beauty
     C0067 2022-11-22 00:00:00         1     219.06       219.06     NaN     Electronics
     C0786 2022-05-19 00:00:00         1     125.69       125.69     NaN   Home & Garden
     C1718 2023-02-10 00:00:00         1     197.49       197.49     NaN        Clothing
     C0017 2022-02-15 00:00:00         1     109.53       109.53     NaN        Clothing
     C0033 2022-07-07 00:00:00         1       8.42         8.42     NaN           Books
     C1718 2023-03-10 00:00:00         1     133.54       117.22     NaN        Clothing
CustomerID            1
InvoiceDate           0
Quantity              0
UnitPrice             0
TotalAmount           0
Country            1339
ProductCategory       0
dtype: int64

#####  The Country column contains 1,339 missing values affecting 281 distinct customers. The available columns are CustomerID, InvoiceDate, Quantity, UnitPrice, TotalAmount, Country, and ProductCategory. Checking CustomerID did not identify any customers whose countries could be confirmed from other records, and the remaining columns do not reliably establish the actual countries. Therefore, I will not guess the missing values or replace them all with the mode. Instead, I will preserve the records and retain the missing values unless reliable information becomes available from the original data source. We can now fill the missing countries with 'Unknown'.

In [ ]:
df["Country"] = df["Country"].fillna("Unknown")

print("Missing Country values after:", df["Country"].isna().sum())
print("Total rows:", len(df))

Missing Country values after: 0
Total rows: 8205

In [ ]:
df.head(20)

,CustomerID,InvoiceDate,Quantity,UnitPrice,TotalAmount,Country,ProductCategory
0,C0045,2022-08-24 00:00:00,2,39.69,79.39,UK,Books
1,C0757,2022-07-01 00:00:00,1,414.09,414.09,Netherlands,Sports
2,C1643,2022-01-05 00:00:00,1,358.44,358.44,Unknown,Sports
3,C0133,2023-07-01 00:00:00,1,150.21,150.21,UK,Clothing
4,C0941,2022-12-10 00:00:00,1,222.65,222.65,UK,Sports
5,C0802,2023-02-20 00:00:00,1,31.98,31.98,UK,Beauty
6,C1284,2022-12-04 00:00:00,1,678.76,678.76,Italy,Electronics
7,C1706,2022-04-24 00:00:00,1,150.28,127.41,UK,Clothing
8,C1608,2022-11-12 00:00:00,1,37.89,37.89,UK,Beauty
9,C0759,2023-03-19 00:00:00,1,38.60,38.60,Spain,Beauty
10,C1735,2022-10-03 00:00:00,1,54.05,54.05,Germany,Beauty
11,C0562,2022-04-20 00:00:00,1,58.12,58.12,UK,Beauty
12,C0363,2023-03-29 00:00:00,1,159.31,159.31,UK,Sports
13,C0224,2022-10-24 00:00:00,1,446.87,446.87,UK,Sports
14,C1802,2022-11-12 00:00:00,1,602.07,602.07,Unknown,Electronics
15,C0970,2022-11-02 00:00:00,5,38.72,193.61,UK,Books
16,C0019,2022-08-20 00:00:00,1,9.65,9.65,France,Books
17,C0790,2022-12-04 00:00:00,1,502.04,502.04,UK,Electronics
18,C0109,2022-07-31 00:00:00,1,96.24,96.24,Unknown,Home & Garden
19,C1591,2022-11-01 00:00:00,1,48.96,48.96,Spain,Clothing