In [ ]:
import pandas as pd
import numpy as np
#the main problems with this datasets are the columns Quantity, UnitPrice, and TotalAmount
#Quantity has negative values,
#UnitPrice have prices that are greater than the TotalAmount and others that dont coordinate with the totalAmount and Quantity values
#TotalAmount has values that that don't coordinate with the Price and Quantity values

In [ ]:
# removing all negative values from the Quantity column and putting it back into the dataset
data = pd.read_csv('ecommerce_data.csv')
data.loc[:,'Quantity']=data.loc[:,'Quantity'].abs()

In [14]:
# With the new quantity values we can calculate a newUnitPrice column by dividing the TotalAmount by the Quality
data['newUnitPrice']=round(data['TotalAmount']/data['Quantity'],2)
data.head(10)

,CustomerID,InvoiceDate,Quantity,UnitPrice,TotalAmount,Country,ProductCategory,newUnitPrice
0,C0045,2022-08-24 00:00:00,2,39.69,79.39,UK,Books,39.70
1,C0757,2022-07-01 00:00:00,1,414.09,414.09,Netherlands,Sports,414.09
2,C1643,2022-01-05 00:00:00,1,358.44,358.44,NaN,Sports,358.44
3,C0133,2023-07-01 00:00:00,1,150.21,150.21,UK,Clothing,150.21
4,C0941,2022-12-10 00:00:00,1,222.65,222.65,UK,Sports,222.65
5,C0802,2023-02-20 00:00:00,1,31.98,31.98,UK,Beauty,31.98
6,C1284,2022-12-04 00:00:00,1,678.76,678.76,Italy,Electronics,678.76
7,C1706,2022-04-24 00:00:00,1,150.28,127.41,UK,Clothing,127.41
8,C1608,2022-11-12 00:00:00,1,37.89,37.89,UK,Beauty,37.89
9,C0759,2023-03-19 00:00:00,1,38.60,38.60,Spain,Beauty,38.60

In [17]:
#Checking to see which UnitPrice are different from the newUnitPrices
data[["TotalAmount", "UnitPrice", "Quantity","newUnitPrice" ]][data["UnitPrice"]!=round(data["newUnitPrice"],2)]

Empty DataFrame
Columns: [TotalAmount, UnitPrice, Quantity, newUnitPrice]
Index: []

In [20]:
#replacing UnitPrice with the new UnitPrice column to make the data more consistent, and removing the newUnitPrice column
data['UnitPrice']=data['newUnitPrice']
data=data.drop(columns='newUnitPrice')

In [18]:
#with the new UnitPrice, the data is now more accurate and ready to be used.
data.head()

,CustomerID,InvoiceDate,Quantity,UnitPrice,TotalAmount,Country,ProductCategory,newUnitPrice
0,C0045,2022-08-24 00:00:00,2,39.70,79.39,UK,Books,39.70
1,C0757,2022-07-01 00:00:00,1,414.09,414.09,Netherlands,Sports,414.09
2,C1643,2022-01-05 00:00:00,1,358.44,358.44,NaN,Sports,358.44
3,C0133,2023-07-01 00:00:00,1,150.21,150.21,UK,Clothing,150.21
4,C0941,2022-12-10 00:00:00,1,222.65,222.65,UK,Sports,222.65